// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Pricing() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- Pricing Section --><section id=\"pricing\" class=\"py-16 bg-gray-50\"><div class=\"container mx-auto px-4\"><h2 class=\"text-4xl font-bold text-center mb-12\">Pricing</h2><div class=\"grid grid-cols-1 md:grid-cols-3 gap-8\"><div class=\"card shadow-lg\"><div class=\"card-body text-center\"><h3 class=\"text-2xl font-bold mb-4\">Basic</h3><p class=\"text-5xl font-bold mb-4\">$10</p><p class=\"mb-4\">Perfect for individuals</p><ul class=\"text-left mb-4\"><li>✔ 5 Projects</li><li>✔ Basic Support</li><li>✔ Community Access</li></ul><a href=\"#\" class=\"btn btn-primary\">Choose Basic</a></div></div><div class=\"card shadow-lg border-2 border-primary\"><div class=\"card-body text-center\"><h3 class=\"text-2xl font-bold mb-4\">Pro</h3><p class=\"text-5xl font-bold mb-4\">$50</p><p class=\"mb-4\">For growing teams</p><ul class=\"text-left mb-4\"><li>✔ 20 Projects</li><li>✔ Priority Support</li><li>✔ Advanced Analytics</li></ul><a href=\"#\" class=\"btn btn-primary\">Choose Pro</a></div></div><div class=\"card shadow-lg\"><div class=\"card-body text-center\"><h3 class=\"text-2xl font-bold mb-4\">Enterprise</h3><p class=\"text-5xl font-bold mb-4\">Contact Us</p><p class=\"mb-4\">For large organizations</p><ul class=\"text-left mb-4\"><li>✔ Unlimited Projects</li><li>✔ Dedicated Support</li><li>✔ Custom Integrations</li></ul><a href=\"#\" class=\"btn btn-primary\">Contact Us</a></div></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
