// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package landing

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LandingHeader() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Header --><header class=\"fixed w-full bg-white shadow-md z-50\"><div class=\"container mx-auto px-4 py-4 flex justify-between items-center\"><a href=\"/\" class=\"text-2xl font-bold text-indigo-600\">BrandName</a><nav class=\"hidden md:flex space-x-6\"><a href=\"#features\" class=\"hover:text-indigo-600\">Features</a> <a href=\"#pricing\" class=\"hover:text-indigo-600\">Pricing</a> <a href=\"#testimonials\" class=\"hover:text-indigo-600\">Testimonials</a> <a href=\"#contact\" class=\"hover:text-indigo-600\">Contact</a></nav><div class=\"space-x-4\"><a href=\"/sign-in\" class=\"btn btn-outline btn-sm\">Sign In</a> <a href=\"/sign-up\" class=\"btn btn-primary btn-sm\">Sign Up</a></div></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
